name: DeepNote Keepalive 5分钟
on:
  schedule:
    - cron: '*/5 0-16 * * *'
    - cron: '*/5 21-23 * * *'
  # 手动触发选项
  workflow_dispatch:
jobs:
  keepalive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      

    - name: Check WEB_URLs Status
      id: check_url_status
      run: |
        # 检查第一个URL
        HTTP_STATUS1=$(curl -s -o /dev/null -w "%{http_code}" -L "${{ secrets.WEB_URL }}")
        echo "WEB_URL status code: $HTTP_STATUS1"
    
        # 检查第二个URL
        HTTP_STATUS2=$(curl -s -o /dev/null -w "%{http_code}" -L "${{ secrets.WEB_URL2 }}")
        echo "WEB_URL2 status code: $HTTP_STATUS2"
    
        # 判断结果
        if [ "$HTTP_STATUS1" = "200" ] && [ "$HTTP_STATUS2" = "200" ]; then
        FINAL_STATUS="200"
        else
        FINAL_STATUS="400"
        fi
    
        # 输出结果到GitHub Actions
        echo "status=$FINAL_STATUS" >> $GITHUB_OUTPUT
        echo "Final status code: $FINAL_STATUS"
        
    - name: Restore cookies cache
      if: steps.check_url_status.outputs.status != '200'
      id: cache-cookies
      uses: actions/cache/restore@v3
      with:
        path: deepnote_cookies.json
        key: deepnote-cookies-v1
        restore-keys: |
          deepnote-cookies-
    
    - name: Set up Python
      if: steps.check_url_status.outputs.status != '200'
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Restore pip cache
      if: steps.check_url_status.outputs.status != '200'
      id: cache-pip
      uses: actions/cache/restore@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Restore Playwright cache
      if: steps.check_url_status.outputs.status != '200'
      id: cache-playwright
      uses: actions/cache/restore@v3
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/playwright.version') }}
        restore-keys: |
          ${{ runner.os }}-playwright-
          
    - name: Create playwright.version file if not exists
      if: steps.check_url_status.outputs.status != '200'
      run: |
        if [ ! -f "playwright.version" ]; then
          playwright_version=$(pip show playwright 2>/dev/null | grep Version | cut -d ' ' -f 2 || echo "1.34.0")
          echo "$playwright_version" > playwright.version
        fi
    
    - name: Install dependencies
      if: steps.check_url_status.outputs.status != '200'
      run: |
        python -m pip install --upgrade pip
        # Install from requirements.txt if it exists
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          pip install playwright
        fi
        # Only install Playwright browsers if cache doesn't exist
        if [ "${{ steps.cache-playwright.outputs.cache-hit }}" != 'true' ]; then
          echo "Installing Playwright browsers..."
          python -m playwright install firefox
        else
          echo "Using cached Playwright browsers"
        fi
        
    - name: Run Python Script on Non-200 Status
      if: steps.check_url_status.outputs.status != '200'
      env:
        # Credentials stored in GitHub Secrets
        GT_PW: ${{ secrets.GT_PW }}
        DEEP_URL: ${{ secrets.DEEP_URL }}
        DEEP_URL2: ${{ secrets.DEEP_URL2 }}
      run: |
        python main.py
        python main2.py
        
    - name: Save cookies cache
      if: steps.check_url_status.outputs.status != '200'
      uses: actions/cache/save@v3
      with:
        path: deepnote_cookies.json
        key: deepnote-cookies-v1
        
    - name: Save pip cache
      if: steps.check_url_status.outputs.status != '200'
      uses: actions/cache/save@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        
    - name: Save Playwright cache
      if: steps.check_url_status.outputs.status != '200'
      uses: actions/cache/save@v3
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/playwright.version') }}
